### ISSUE TITLE
Depricated Numpy and 'Planck_highl' object has no attribute 'path_clik'

### ISSUE THREAD

**Issue by purba13194** [baudren/montepython_public#108]
Dear Sir,

        I am facing this problem as I run my codes. The details are given below as an attachment. I would be grateful if anyone could help me i this context.

[pm14ip011@hpc code]$ python montepython/MontePython.py run -p base2015.param -o outdir/ -b bestfit/base2015.bestfit -c covmat/base2015.covmat --conf my.conf
Running Monte Python v2.2.2

with CLASS v2.6.3

Testing likelihoods for:
 -> Planck_highl, Planck_lowl, Planck_lensing

RuntimeError: module compiled against API version 0xa but this version of numpy is 0x7
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/run.py", line 31, in run
    custom_command)
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/run.py", line 188, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/initialise.py", line 66, in initialise
    data = Data(command_line, path)
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/data.py", line 340, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/data.py", line 460, in initialise_likelihoods
    elem, elem, folder, elem)
  File "<string>", line 1, in <module>
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/likelihood_class.py", line 863, in __init__
    self.clik = clik.clik(self.path_clik)
AttributeError: 'Planck_highl' object has no attribute 'path_clik'

**Comment by brinckmann** [comment]
See reply by Deanna to your other post in issue #94, as well as instructions in issue #68.
Best,
Thejs
