### ISSUE TITLE
Problem with sne likelihood data. Please help.

### ISSUE THREAD

**Issue by purba13194** [baudren/montepython_public#109]
I was trying to use MontePython with SNe data, and evertime I'm getting the same error.
I have checked that I am also having the latest version of MontePython.

[pm14ip011@hpc code]$ python montepython/MontePython.py info chains/lckb_sne
Running Monte Python v2.2.2

--> Finding global maximum of likelihood
--> Removing burn-in
--> Scanning file chains/lckb_sne/2018-03-12_100000__8.txt : Removed 0 non-markovian points, 0 points of burn-in, keep 24115 steps
                                  2018-03-12_100000__5.txt : Removed 0 non-markovian points, 1 points of burn-in, keep 23843 steps
                                  2018-03-12_100000__1.txt : Removed 0 non-markovian points, 3 points of burn-in, keep 23902 steps
                                  2018-03-12_100000__7.txt : Removed 0 non-markovian points, 3 points of burn-in, keep 23326 steps
                                  2018-03-12_100000__3.txt : Removed 0 non-markovian points, 1 points of burn-in, keep 24007 steps
                                  2018-03-12_100000__6.txt : Removed 0 non-markovian points, 0 points of burn-in, keep 24014 steps
                                  2018-03-12_100000__2.txt : Removed 0 non-markovian points, 0 points of burn-in, keep 23901 steps
                                  2018-03-12_100000__4.txt : Removed 0 non-markovian points, 0 points of burn-in, keep 23751 steps
--> Computing mean values
--> Computing variance
--> Computing convergence criterium (Gelman-Rubin)
 -> R-1 is 0.007863 	for  Omega_b
           0.004751 	for  Omega_cdm
           0.000726 	for  Omega_k
           0.000493 	for  Omega_Lambda
-----------------------------------------------
 -> Computing histograms for  Omega_b
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/run.py", line 31, in run
    custom_command)
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/run.py", line 188, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/initialise.py", line 58, in initialise
    analyze(command_line)
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/analyze.py", line 128, in analyze
    compute_posterior(information_instances)
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/analyze.py", line 460, in compute_posterior
    bounds = minimum_credible_intervals(info)
  File "/home/pm14ip011/MontePy_Workspace/code/montepython/analyze.py", line 757, in minimum_credible_intervals
    left_edge = np.max(histogram[0] - 0.5*(histogram[1]-histogram[0]), 0.)
  File "/MS/pm14ip011/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2317, in amax
    return amax(axis=axis, out=out, **kwargs)
  File "/MS/pm14ip011/.local/lib/python2.7/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
TypeError: 'float' object cannot be interpreted as an index

**Comment by brinckmann** [comment]
I believe this is the same problem as issue #84, did you try the fix proposed by ardok?
Best,
Thejs
