### ISSUE TITLE
Module has no attribute 'lkl'

### ISSUE THREAD

**Issue by DinorahBarbosa** [baudren/montepython_public#131]
Hi, I've been trying to reproduce the data of an article using Planck's 2013 likelihood. I followed the steps for installing and usage but I keep getting the following error:

python montepython/MontePython.py run -p input/planck+pantheon2.param -o chains/deltaw0 -N 1000
Running Monte Python v3.0.1

with CLASS v2.7.1

Testing likelihoods for:
 -> Planck_actspt, Planck_highl, Planck_lowl, Planck_lensing, Pantheon, bao

Cannot use clik wrapper (cause = 'No module named lkl')
Cannot use clik_lensing wrapper (cause = 'No module named lkl_lensing')
Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/dinorah/montepython_public/montepython/run.py", line 31, in run
    custom_command)
  File "/home/dinorah/montepython_public/montepython/run.py", line 188, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/dinorah/montepython_public/montepython/initialise.py", line 66, in initialise
    data = Data(command_line, path)
  File "/home/dinorah/montepython_public/montepython/data.py", line 341, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/dinorah/montepython_public/montepython/data.py", line 470, in initialise_likelihoods
    elem, elem, folder, elem)
  File "<string>", line 1, in <module>
  File "/home/dinorah/montepython_public/montepython/likelihood_class.py", line 886, in __init__
    except clik.lkl.CError:
AttributeError: 'module' object has no attribute 'lkl'

I don't understand what I did wrong, I have configured all the files correctly...

**Comment by sphericalharmonics** [comment]
Hello, is this issue resolved? I have exactly the same error. plc-3.01 seems to run fine individiually, so does MontePython, but they throw this error when combined.

**Comment by brinckmann** [comment]
Dear user,
Your are raising issues on the old MontePython v1 and v2 repository (active in 2013-2018).
As clearly stated on this wiki, issue #55: since April 2018 and v3, the MontePython repository has moved to https://github.com/brinckmann/montepython_public
Please go there to clone a recent, working and maintained version of the code. Then, if necessary, plaise raise your issues in that repository.
