### ISSUE TITLE
Problem in using sdss_lrgDR7 likelihood

### ISSUE THREAD

**Issue by Antara-Dey** [baudren/montepython_public#146]
Dear all,

              I am new to the code. I am trying to use montepython_public-3.4 version with sdss_lrgDR7 data and I am getting this following error. I could not understand how to resolve it. Thanks in advance.

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/run.py", line 45, in run
    sampler.run(cosmo, data, command_line)
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/sampler.py", line 46, in run
    mcmc.chain(cosmo, data, command_line)
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/mcmc.py", line 787, in chain
    newloglike = sampler.compute_lkl(cosmo, data)
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/sampler.py", line 776, in compute_lkl
    value = likelihood.loglkl(cosmo, data)
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/likelihood_class.py", line 2090, in loglkl
    Psmooth_nl = self.remove_bao(kh,Pnl)
  File "/home/isipamu2/class_montepython/montepython_public-3.4/montepython/likelihood_class.py", line 2327, in remove_bao
    wtrend = scipy.interpolate.UnivariateSpline(wzeros, fwiggle(wzeros), k=3, s=0)
  File "/usr/local/lib/python2.7/dist-packages/scipy/interpolate/fitpack2.py", line 186, in __init__
    xe=bbox[1], s=s)
dfitpack.error: (m>k) failed for hidden m: fpcurf0:m=1

**Comment by lesgourg** [comment]
Dear user,
Your are raising issues on the old MontePython v1 and v2 repository (active in 2013-2018). 
As clearly stated on this wiki, issue #55: since April 2018 and v3, the MontePython repository has moved to https://github.com/brinckmann/montepython_public
Please go there to clone a recent, working and maintained version of the code. Then, if necessary, plaise raise your issues in that repository.
