### ISSUE TITLE
Plotting command does not work for the experiment of example param , failed to get plots , 

### ISSUE THREAD

**Issue by raj1996cool** [baudren/montepython_public#150]
This is the error is called :
raj@ubuntu:~/Documents/code/montepython_public-2.2.2$ python montepython/MontePython.py test/2022-06-28_500__1_*--bins 10
 /!\ Defaulting to the 'run' command. Please update the call of MontePython. For
     more info, see the help string and/or the documentation

Configuration Error:
 /|\   unrecognized arguments: test/2022-06-28_500__1_*--bins 10

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/raj/Documents/code/montepython_public-2.2.2/montepython/run.py", line 31, in run
    custom_command)
  File "/home/raj/Documents/code/montepython_public-2.2.2/montepython/run.py", line 195, in safe_initialisation
    "The initialisation was not successful, resulting in a "
io_mp.ConfigurationError: 

Configuration Error:
 /|\   The initialisation was not successful, resulting in a potentially half
/_o_\  created `log.param`. Please see the above error message. If you run the
       exact same command, it will not work. You should solve the problem, and
       try again.

**Comment by brinckmann** [comment]
Dear user,
Your are raising issues on the old MontePython v1 and v2 repository (active in 2013-2018).
As clearly stated on this wiki, issue https://github.com/baudren/montepython_public/issues/55: since April 2018 and v3, the MontePython repository has moved to https://github.com/brinckmann/montepython_public
Please go there to clone a recent, working and maintained version of the code. Then, if necessary, please raise your issues in that repository.
(this particular problem appears to be because you don't have a space between the file path and the `--bins 10` flag)
Best,
Thejs
