### ISSUE TITLE
Error on using info command of MontePython to analyse chains

### ISSUE THREAD

**Issue by nouicer** [baudren/montepython_public#156]
I am facing an strange issue while using info to produce analyzes and plots of my txt outputs.
I suspected that it was the version of numpy that was not the right one (because of "normed" and "density" for the histograms). But I couldn't find a solution. Here is my error message and hope someone can help me.

Thank you so much

-> Computing histograms for  Omega_m
Traceback (most recent call last):
  File "/home/nouicer/montepython-3.6/montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/nouicer/montepython-3.6/montepython/run.py", line 31, in run
    cosmo, data, command_line, success = safe_initialisation(
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/home/nouicer/montepython-3.6/montepython/run.py", line 191, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nouicer/montepython-3.6/montepython/initialise.py", line 59, in initialise
    analyze(command_line)
  File "/home/nouicer/montepython-3.6/montepython/analyze.py", line 167, in analyze
    compute_posterior(information_instances)
  File "/home/nouicer/montepython-3.6/montepython/analyze.py", line 569, in compute_posterior
    info.hist, info.bin_edges = np.histogram(
                                ^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 198, in histogram
TypeError: histogram() got an unexpected keyword argument 'normed'

**Comment by brinckmann** [comment]
Dear user,
Your are raising issues on the old MontePython v1 and v2 repository (active in 2013-2018).
As clearly stated on this wiki, issue https://github.com/baudren/montepython_public/issues/55: since April 2018 and v3, the MontePython repository has moved to https://github.com/brinckmann/montepython_public
Please go there to clone a recent, working and maintained version of the code. Then, if necessary, please raise your issues in that repository.
(In this particular case, you are re-raising issue https://github.com/brinckmann/montepython_public/issues/318 . This has been fixed on the devel branch and will be pushed public in the next version, in the meantime the issue provides the solution: anywhere in analyze.py where 'normed' is used for histogram or histogram2d it should use 'density' instead)
Best,
Thejs
