### ISSUE TITLE
Likelihoods can not be found.

### ISSUE THREAD

**Issue by bthorne93** [baudren/montepython_public#61]
Hi, I've been trying to install this on two different systems and am getting the same error with the likelihoods: 

```
with CLASS v2.5.0
 /!\ Detecting empty folder, logging the parameter file

Testing likelihoods for:
 -> JLA

Configuration Error:
 /|\   Trying to import the JLA likelihood as asked in the parameter file, and
/_o_\  failed. Please make sure it is in the `montepython/likelihoods` folder,
       and is a proper python module. Check also that the name of the class
       defined in the __init__.py matches the name of the folder. In case this
       is not enough, here is the original message: No module named
       likelihoods.JLA

Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/ben.thorne/montepython_public/montepython/run.py", line 31, in run
    custom_command)
  File "/home/ben.thorne/montepython_public/montepython/run.py", line 195, in safe_initialisation
    "The initialisation was not successful, resulting in a "
io_mp.ConfigurationError: 

Configuration Error:
 /|\   The initialisation was not successful, resulting in a potentially half
/_o_\  created `log.param`. Please see the above error message. If you run the
       exact same command, it will not work. You should solve the problem, and
       try again.
```

The names of folders and classes certainly match.  I have just followed the installation docs and am using python 2.7. The problem persists for any choice of the default likelihoods, including the downloaded plc.
Thanks!

**Comment by miguelzuma** [comment]
Hi,

I had exactly the same problem running montepython in a new laptop. The problem went away on its own (probably due to some update), but before I noticed that I didn't had it when switching to a previous version (I think 2.1 was fine).

You can try a previous version (type 'git checkout 2.1' in the terminal). If it works then you can compare both versions and try to find what's different.
