### ISSUE TITLE
installation of Planck likelihood code

### ISSUE THREAD

**Issue by mahtaparsa** [baudren/montepython_public#68]
Hi everybody,
I have problem with installing the Planck likelihood code (plc). It is advised that we configure clik with mkl library not with lapack. However, when I execute './waf configure --install_all_deps --mkl=$MKLROOT' from the plc directory, the error 'waf: error: no such option: --mkl' would appear, so I configured plc by './waf configure' . With executing './waf configure', configuration would finish successfully, however when I execute './waf install' the following error would appear which I can not solve it:

Build failed
Traceback (most recent call last):
  File "/home/.../plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Runner.py", line 150, in task_status
    return tsk.runnable_status()
  File "/home/.../plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Tools/fc.py", line 46, in runnable_status
    ret=tsk.runnable_status()
  File "/home/.../plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Tools/fc.py", line 40, in runnable_status
    return super(fc,self).runnable_status()
  File "/home/.../plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Task.py", line 313, in runnable_status
    new_sig=self.signature()
  File "/home/.../plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Task.py", line 302, in signature
    self.sig_implicit_deps()
  File "/home/.../plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Task.py", line 386, in sig_implicit_deps
    if prev==self.compute_sig_implicit_deps():
  File "/home/.../plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Task.py", line 424, in compute_sig_implicit_deps
    upd(k.get_bld_sig())
  File "/home/.../plc-2.0/.waf-1.8.8-eab538dea2e33915d3770ff3f393b18b/waflib/Node.py", line 459, in get_bld_sig
    self.cache_sig=ret=self.sig
AttributeError: sig

Please guide me to solve this problem.

**Comment by borisbolliet** [comment]
Dear mahtaparsa, 

Bellow are some instruction I had written down:

In order to install the Planck likelihood, move to plc-2.0/. If you have a recent and tidy computer this step may take only a few seconds, using a tool called waf provided inside the plc-2.0/ folder.

On Mac, just type:

./waf configure --install_all_deps
./waf install

Although, before that you might want to do:

sudo port selfupdate
sudo port upgrade outdated

On Linux (with ifort and mkl):

./waf configure --install_all_deps --lapack_mkl=$MKLROOT
./waf install

On the cluster, at CC-in2p3, I had to do:

./waf configure --install_all_deps --lapack_mkl=/usr/local/intel/mkl/ --ifort
./waf install

If this procedure fails, you should install using make, after having checked that all the necessary libraries are well linked (see readme.md inside plc-2.0/).

Then you can copy the line:

source /PATH/TO/plc-2.0/bin/clik_profile.sh

into your bash_profile and do:

. ~/.bash_profile

to reload your profile file.

**Comment by mahtaparsa** [comment]
Hi Boris,
Thanks for your reply.
