### ISSUE TITLE
Missing pywlik in wrapper_wmap

### ISSUE THREAD

**Issue by F-W-Yang** [baudren/montepython_public#95]
Hi,

all. After I finished installing wrapper_wmap and setting the environment variables, I tried to use the wmap experiment to fit cosmological parameters. However, it returned the error
```    
  Traceback (most recent call last):
  File "montepython/MontePython.py", line 40, in <module>
    sys.exit(run())
  File "/home/fwyang/montepython_public-2.2/montepython/run.py", line 31, in run
    custom_command)
  File "/home/fwyang/montepython_public-2.2/montepython/run.py", line 188, in safe_initialisation
    cosmo, data, command_line, success = initialise(custom_command)
  File "/home/fwyang/montepython_public-2.2/montepython/initialise.py", line 66, in initialise
    data = Data(command_line, path)
  File "/home/fwyang/montepython_public-2.2/montepython/data.py", line 340, in __init__
    self.initialise_likelihoods(self.experiments)
  File "/home/fwyang/montepython_public-2.2/montepython/data.py", line 460, in initialise_likelihoods
    elem, elem, folder, elem)
  File "<string>", line 1, in <module>
  File "/home/fwyang/montepython_public-2.2/montepython/likelihoods/wmap/__init__.py", line 24, in __init__
    "and try again.")
montepython.io_mp.MissingLibraryError: 

Missing Library Error:
 /|\   You must first activate the binaries from the wmap wrapper. Please run :
/_o_\  ]$ source /path/to/wrapper_wmap/bin/clik_profile.sh
       and try again.
```
In clik_profile.sh file, the **PYTHONPATH** is

    PYTHONPATH=/home/fwyang/montepython_public-2.2/wrapper_wmap/lib/python2.7/site-packages
However, there is no directory python2.7/site-packages in wrapper_wmap/lib.

The installation commands show as follow:

    ./waf configure --install_all_deps --lapack_mkl=/opt/intel/mkl --lapack_mkl_version=10.3
    ./waf install
**And the installation has no error message**.

So, I don't know how to install the pywlik module. Could anyone give some suggestion?

Thanks.

**Comment by borisbolliet** [comment]
Hi,

Did you actually execute the command:

`$ source /path/to/wrapper_wmap/bin/clik_profile.sh`

after your clik installation, and before running MontePython ?

Boris

**Comment by F-W-Yang** [comment]
Hi,

@borisbolliet. Actually, by setting the environment variables, I means I have sourced the file clik_profile.sh in wrapper_wmap/bin/ .

Fengwei

**Comment by borisbolliet** [comment]
Ah! good, then like you say it may be a problem of locations of your python modules. 

But this seems strange, because 'waf' generates the *.sh file automatically, and the path written in it should be correct...

Good luck,

Boris

**Comment by F-W-Yang** [comment]
@borisbolliet, did you use the WMAP experiment before? Could you send me the directory python2.7/site-packages in wrapper_wmap/lib by email? Now I have no other idea to install the wmap wrapper correctly.

My email address is yfw0123@outlook.com.

**Comment by borisbolliet** [comment]
Well, actually I have only been working with Planck data so far... (which works in a similar way as for WMAP).

It is likely that your problem if related to an ambiguity between different python versions on your machine. 

You  shall make sure that the Python version used by Montepython is the same as the one pointed by clik...

**Comment by bufeo** [comment]
Hi Fengwei

I'm having exactly the same problem as you described. Did you manage to solve it?
There is a file "wrapper_wmap/src/python/pywlik.pyx" but it seems not to be compiled when executing waf.

Cheers,
Julia
